### ISSUE TITLE
refining API

### ISSUE THREAD

**Issue by jakejh** [hugheylab/co-occurence_statistics#1]
Here are two things that would be useful:
- return the names of columns
- allow case-insensitive regex search by ingredient name and phecode name

The code I ran is below.

```r
library('data.table')
library('httr')

urlBase = 'http://18.220.193.105/general_exposure?ids='
ingredIds = c(40230597, 46274210, 1705674, 703547)
urlFull = paste0(urlBase, paste(ingredIds, collapse = ','))

a1 = GET(urlFull)
a2 = content(a1, 'parsed')
```

**Comment by JSchoenbachler** [comment]
The below commit resolved the returning of the column names:

https://github.com/hugheylab/co-occurence_statistics/commit/671e70e409ca96d99503ca9a069603f2bee6533c

Still working on applying the search of the ingredient name.

**Comment by JSchoenbachler** [comment]
The below commits added the lowercase regex searching of ingredient_name onto the general exposure endpoint:

https://github.com/hugheylab/co-occurence_statistics/commit/856c09a2ded94460f48172c662567fbbdd01f711 - Initial Add

https://github.com/hugheylab/co-occurence_statistics/commit/b0ccf292df8e2eb9c8b66a01a5907fdc2b2b6638 - Bug Fix on Query

https://github.com/hugheylab/co-occurence_statistics/commit/8f20743a29186a40645fd02425229d7f7e8946fd - Make the search case-insensitive rather than case sensitive
